<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Authors>Shoaib Ali</Authors>
    <PackAsTool>False</PackAsTool>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <PackageId>EmbeddedPostgres</PackageId>
    <PackageTags>postgres;postgresql;pg;embed;embedded;server;.net 10;net 10.0;.net core;.net;</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/alleey/EmbeddedPostgres</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/alleey/EmbeddedPostgres</RepositoryUrl>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <Copyright>Shoaib Ali</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmbeddedPostgres.Core\EmbeddedPostgres.Core.csproj" />
  </ItemGroup>

</Project>
